-- Create table
create table BACKUP.EVN_AP_SELF_ASSESSED_TAX_DIST
(
  invoice_distribution_id      NUMBER(15) not null,
  org_id                       NUMBER(15) not null,
  accounting_date              DATE not null,
  accrual_posted_flag          VARCHAR2(1) not null,
  assets_addition_flag         VARCHAR2(1) not null,
  assets_tracking_flag         VARCHAR2(1) not null,
  cash_posted_flag             VARCHAR2(1) not null,
  distribution_line_number     NUMBER(15) not null,
  dist_code_combination_id     NUMBER(15) not null,
  invoice_id                   NUMBER(15) not null,
  last_updated_by              NUMBER(15) not null,
  last_update_date             DATE not null,
  line_type_lookup_code        VARCHAR2(25) not null,
  period_name                  VARCHAR2(15) not null,
  set_of_books_id              NUMBER(15) not null,
  self_assessed_flag           VARCHAR2(1) not null,
  amount                       NUMBER,
  base_amount                  NUMBER,
  batch_id                     NUMBER(15),
  created_by                   NUMBER(15),
  creation_date                DATE,
  description                  VARCHAR2(240),
  final_match_flag             VARCHAR2(1),
  income_tax_region            VARCHAR2(10),
  last_update_login            NUMBER(15),
  match_status_flag            VARCHAR2(1),
  posted_flag                  VARCHAR2(1),
  po_distribution_id           NUMBER(15),
  program_application_id       NUMBER(15),
  program_id                   NUMBER(15),
  program_update_date          DATE,
  quantity_invoiced            NUMBER,
  request_id                   NUMBER(15),
  reversal_flag                VARCHAR2(1),
  type_1099                    VARCHAR2(10),
  unit_price                   NUMBER,
  encumbered_flag              VARCHAR2(1),
  stat_amount                  NUMBER,
  expenditure_item_date        DATE,
  expenditure_organization_id  NUMBER(15),
  expenditure_type             VARCHAR2(30),
  parent_invoice_id            NUMBER(15),
  pa_addition_flag             VARCHAR2(1),
  pa_quantity                  NUMBER(22),
  prepay_amount_remaining      NUMBER,
  project_id                   NUMBER(15),
  task_id                      NUMBER(15),
  ussgl_transaction_code       VARCHAR2(30),
  ussgl_trx_code_context       VARCHAR2(30),
  quantity_variance            NUMBER,
  base_quantity_variance       NUMBER,
  packet_id                    NUMBER(15),
  awt_flag                     VARCHAR2(1),
  awt_group_id                 NUMBER(15),
  awt_tax_rate_id              NUMBER(15),
  awt_gross_amount             NUMBER,
  awt_invoice_id               NUMBER(15),
  awt_origin_group_id          NUMBER(15),
  reference_1                  VARCHAR2(30),
  reference_2                  VARCHAR2(30),
  awt_invoice_payment_id       NUMBER(15),
  receipt_verified_flag        VARCHAR2(1),
  receipt_required_flag        VARCHAR2(1),
  receipt_missing_flag         VARCHAR2(1),
  justification                VARCHAR2(240),
  expense_group                VARCHAR2(80),
  start_expense_date           DATE,
  end_expense_date             DATE,
  receipt_currency_code        VARCHAR2(15),
  receipt_conversion_rate      NUMBER,
  receipt_currency_amount      NUMBER,
  daily_amount                 NUMBER,
  web_parameter_id             NUMBER,
  adjustment_reason            VARCHAR2(240),
  award_id                     NUMBER(15),
  dist_match_type              VARCHAR2(25),
  rcv_transaction_id           NUMBER(15),
  parent_reversal_id           NUMBER(15),
  tax_recoverable_flag         VARCHAR2(1),
  tax_code_id                  NUMBER(15),
  merchant_document_number     VARCHAR2(80),
  merchant_name                VARCHAR2(80),
  merchant_reference           VARCHAR2(240),
  merchant_tax_reg_number      VARCHAR2(80),
  merchant_taxpayer_id         VARCHAR2(80),
  country_of_supply            VARCHAR2(5),
  matched_uom_lookup_code      VARCHAR2(25),
  gms_burdenable_raw_cost      NUMBER(22),
  accounting_event_id          NUMBER(15),
  prepay_distribution_id       NUMBER(15),
  credit_card_trx_id           NUMBER(15),
  upgrade_posted_amt           NUMBER,
  upgrade_base_posted_amt      NUMBER,
  inventory_transfer_status    VARCHAR2(1),
  company_prepaid_invoice_id   NUMBER(15),
  cc_reversal_flag             VARCHAR2(1),
  awt_withheld_amt             NUMBER,
  pa_cmt_xface_flag            VARCHAR2(1),
  cancellation_flag            VARCHAR2(1),
  invoice_line_number          NUMBER,
  rounding_amt                 NUMBER,
  charge_applicable_to_dist_id NUMBER(15),
  corrected_invoice_dist_id    NUMBER(15),
  corrected_quantity           NUMBER,
  related_id                   NUMBER(15),
  asset_book_type_code         VARCHAR2(15),
  asset_category_id            NUMBER(15),
  distribution_class           VARCHAR2(30),
  intended_use                 VARCHAR2(30),
  detail_tax_dist_id           NUMBER,
  rec_nrec_rate                NUMBER,
  recovery_rate_id             NUMBER,
  recovery_rate_name           VARCHAR2(30),
  recovery_type_code           VARCHAR2(30),
  withholding_tax_code_id      NUMBER(15),
  tax_already_distributed_flag VARCHAR2(1),
  summary_tax_line_id          NUMBER,
  taxable_amount               NUMBER,
  taxable_base_amount          NUMBER,
  prepay_tax_diff_amount       NUMBER,
  extra_po_erv                 NUMBER,
  self_assessed_tax_liab_ccid  NUMBER(15),
  attribute_category           VARCHAR2(150),
  attribute1                   VARCHAR2(150),
  attribute2                   VARCHAR2(150),
  attribute3                   VARCHAR2(150),
  attribute4                   VARCHAR2(150),
  attribute5                   VARCHAR2(150),
  attribute6                   VARCHAR2(150),
  attribute7                   VARCHAR2(150),
  attribute8                   VARCHAR2(150),
  attribute9                   VARCHAR2(150),
  attribute10                  VARCHAR2(150),
  attribute11                  VARCHAR2(150),
  attribute12                  VARCHAR2(150),
  attribute13                  VARCHAR2(150),
  attribute14                  VARCHAR2(150),
  attribute15                  VARCHAR2(150),
  global_attribute_category    VARCHAR2(150),
  global_attribute1            VARCHAR2(150),
  global_attribute2            VARCHAR2(150),
  global_attribute3            VARCHAR2(150),
  global_attribute4            VARCHAR2(150),
  global_attribute5            VARCHAR2(150),
  global_attribute6            VARCHAR2(150),
  global_attribute7            VARCHAR2(150),
  global_attribute8            VARCHAR2(150),
  global_attribute9            VARCHAR2(150),
  global_attribute10           VARCHAR2(150),
  global_attribute11           VARCHAR2(150),
  global_attribute12           VARCHAR2(150),
  global_attribute13           VARCHAR2(150),
  global_attribute14           VARCHAR2(150),
  global_attribute15           VARCHAR2(150),
  global_attribute16           VARCHAR2(150),
  global_attribute17           VARCHAR2(150),
  global_attribute18           VARCHAR2(150),
  global_attribute19           VARCHAR2(150),
  global_attribute20           VARCHAR2(150),
  project_accounting_context   VARCHAR2(30),
  rcv_charge_addition_flag     VARCHAR2(1),
  bc_event_id                  NUMBER(15),
  amount_variance              NUMBER,
  base_amount_variance         NUMBER
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 128K
    next 128K
    minextents 1
    maxextents unlimited
    pctincrease 0
  );
