-- Create table
create table BACKUP.EVN_XLA_DISTRIBUTION_LINKS_BAK
(
  application_id                NUMBER(15) not null,
  event_id                      NUMBER(15) not null,
  ae_header_id                  NUMBER(15) not null,
  ae_line_num                   NUMBER(38) not null,
  source_distribution_type      VARCHAR2(30) not null,
  source_distribution_id_char_1 VARCHAR2(240),
  source_distribution_id_char_2 VARCHAR2(240),
  source_distribution_id_char_3 VARCHAR2(240),
  source_distribution_id_char_4 VARCHAR2(240),
  source_distribution_id_char_5 VARCHAR2(240),
  source_distribution_id_num_1  NUMBER(38),
  source_distribution_id_num_2  NUMBER(38),
  source_distribution_id_num_3  NUMBER(38),
  source_distribution_id_num_4  NUMBER(38),
  source_distribution_id_num_5  NUMBER(38),
  tax_line_ref_id               NUMBER(15),
  tax_summary_line_ref_id       NUMBER(15),
  tax_rec_nrec_dist_ref_id      NUMBER(15),
  statistical_amount            NUMBER,
  ref_ae_header_id              NUMBER(15) not null,
  ref_temp_line_num             NUMBER(15),
  accounting_line_code          VARCHAR2(30),
  accounting_line_type_code     VARCHAR2(1),
  merge_duplicate_code          VARCHAR2(1) not null,
  temp_line_num                 NUMBER(15) not null,
  ref_event_id                  NUMBER(15),
  line_definition_owner_code    VARCHAR2(30),
  line_definition_code          VARCHAR2(30),
  event_class_code              VARCHAR2(30),
  event_type_code               VARCHAR2(30),
  upg_batch_id                  NUMBER(15),
  calculate_acctd_amts_flag     VARCHAR2(1),
  calculate_g_l_amts_flag       VARCHAR2(1),
  rounding_class_code           VARCHAR2(30),
  document_rounding_level       VARCHAR2(30),
  unrounded_entered_dr          NUMBER,
  unrounded_entered_cr          NUMBER,
  doc_rounding_entered_amt      NUMBER,
  doc_rounding_acctd_amt        NUMBER,
  unrounded_accounted_cr        NUMBER,
  unrounded_accounted_dr        NUMBER,
  applied_to_application_id     NUMBER(15),
  applied_to_entity_code        VARCHAR2(30),
  applied_to_entity_id          NUMBER(15),
  applied_to_source_id_num_1    NUMBER(15),
  applied_to_source_id_num_2    NUMBER(15),
  applied_to_source_id_num_3    NUMBER(15),
  applied_to_source_id_num_4    NUMBER(15),
  applied_to_source_id_char_1   VARCHAR2(30),
  applied_to_source_id_char_2   VARCHAR2(30),
  applied_to_source_id_char_3   VARCHAR2(30),
  applied_to_source_id_char_4   VARCHAR2(30),
  applied_to_distribution_type  VARCHAR2(30),
  applied_to_dist_id_num_1      NUMBER(15),
  applied_to_dist_id_num_2      NUMBER(15),
  applied_to_dist_id_num_3      NUMBER(15),
  applied_to_dist_id_num_4      NUMBER(15),
  applied_to_dist_id_num_5      NUMBER(15),
  applied_to_dist_id_char_1     VARCHAR2(30),
  applied_to_dist_id_char_2     VARCHAR2(30),
  applied_to_dist_id_char_3     VARCHAR2(30),
  applied_to_dist_id_char_4     VARCHAR2(30),
  applied_to_dist_id_char_5     VARCHAR2(30),
  alloc_to_application_id       NUMBER(15),
  alloc_to_entity_code          VARCHAR2(30),
  alloc_to_source_id_num_1      NUMBER(15),
  alloc_to_source_id_num_2      NUMBER(15),
  alloc_to_source_id_num_3      NUMBER(15),
  alloc_to_source_id_num_4      NUMBER(15),
  alloc_to_source_id_char_1     VARCHAR2(30),
  alloc_to_source_id_char_2     VARCHAR2(30),
  alloc_to_source_id_char_3     VARCHAR2(30),
  alloc_to_source_id_char_4     VARCHAR2(30),
  alloc_to_distribution_type    VARCHAR2(30),
  alloc_to_dist_id_num_1        NUMBER(15),
  alloc_to_dist_id_num_2        NUMBER(15),
  alloc_to_dist_id_num_3        NUMBER(15),
  alloc_to_dist_id_num_4        NUMBER(15),
  alloc_to_dist_id_num_5        NUMBER(15),
  alloc_to_dist_id_char_1       VARCHAR2(30),
  alloc_to_dist_id_char_2       VARCHAR2(30),
  alloc_to_dist_id_char_3       VARCHAR2(30),
  alloc_to_dist_id_char_4       VARCHAR2(30),
  alloc_to_dist_id_char_5       VARCHAR2(30),
  gain_or_loss_ref              VARCHAR2(30)
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 128K
    next 128K
    minextents 1
    maxextents unlimited
    pctincrease 0
  );
