-- Create table
create table BACKUP.evn_ar_receivable_appl_b3
(
  receivable_application_id      NUMBER(15) not null,
  last_updated_by                NUMBER(15) not null,
  last_update_date               DATE not null,
  created_by                     NUMBER(15) not null,
  creation_date                  DATE not null,
  amount_applied                 NUMBER not null,
  amount_applied_from            NUMBER,
  trans_to_receipt_rate          NUMBER,
  gl_date                        DATE not null,
  code_combination_id            NUMBER(15) not null,
  set_of_books_id                NUMBER(15) not null,
  display                        VARCHAR2(1) not null,
  apply_date                     DATE not null,
  application_type               VARCHAR2(20) not null,
  status                         VARCHAR2(30) not null,
  payment_schedule_id            NUMBER(15) not null,
  last_update_login              NUMBER(15),
  cash_receipt_id                NUMBER(15),
  applied_customer_trx_id        NUMBER(15),
  applied_customer_trx_line_id   NUMBER(15),
  applied_payment_schedule_id    NUMBER(15),
  customer_trx_id                NUMBER(15),
  line_applied                   NUMBER,
  tax_applied                    NUMBER,
  freight_applied                NUMBER,
  receivables_charges_applied    NUMBER,
  earned_discount_taken          NUMBER,
  unearned_discount_taken        NUMBER,
  days_late                      NUMBER(15),
  application_rule               VARCHAR2(30) not null,
  gl_posted_date                 DATE,
  comments                       VARCHAR2(240),
  attribute_category             VARCHAR2(30),
  attribute1                     VARCHAR2(150),
  attribute2                     VARCHAR2(150),
  attribute3                     VARCHAR2(150),
  attribute4                     VARCHAR2(150),
  attribute5                     VARCHAR2(150),
  attribute6                     VARCHAR2(150),
  attribute7                     VARCHAR2(150),
  attribute8                     VARCHAR2(150),
  attribute9                     VARCHAR2(150),
  attribute10                    VARCHAR2(150),
  postable                       VARCHAR2(1),
  posting_control_id             NUMBER(15) default -3 not null,
  acctd_amount_applied_from      NUMBER not null,
  acctd_amount_applied_to        NUMBER,
  acctd_earned_discount_taken    NUMBER,
  attribute11                    VARCHAR2(150),
  attribute12                    VARCHAR2(150),
  attribute13                    VARCHAR2(150),
  attribute14                    VARCHAR2(150),
  attribute15                    VARCHAR2(150),
  confirmed_flag                 VARCHAR2(1),
  program_application_id         NUMBER(15),
  program_id                     NUMBER(15),
  program_update_date            DATE,
  request_id                     NUMBER(15),
  ussgl_transaction_code         VARCHAR2(30),
  ussgl_transaction_code_context VARCHAR2(30),
  earned_discount_ccid           NUMBER(15),
  unearned_discount_ccid         NUMBER(15),
  acctd_unearned_discount_taken  NUMBER,
  reversal_gl_date               DATE,
  cash_receipt_history_id        NUMBER(15),
  org_id                         NUMBER(15),
  tax_code                       VARCHAR2(50),
  global_attribute1              VARCHAR2(150),
  global_attribute2              VARCHAR2(150),
  global_attribute3              VARCHAR2(150),
  global_attribute4              VARCHAR2(150),
  global_attribute5              VARCHAR2(150),
  global_attribute6              VARCHAR2(150),
  global_attribute7              VARCHAR2(150),
  global_attribute8              VARCHAR2(150),
  global_attribute9              VARCHAR2(150),
  global_attribute10             VARCHAR2(150),
  global_attribute11             VARCHAR2(150),
  global_attribute12             VARCHAR2(150),
  global_attribute13             VARCHAR2(150),
  global_attribute14             VARCHAR2(150),
  global_attribute15             VARCHAR2(150),
  global_attribute16             VARCHAR2(150),
  global_attribute17             VARCHAR2(150),
  global_attribute18             VARCHAR2(150),
  global_attribute19             VARCHAR2(150),
  global_attribute20             VARCHAR2(150),
  global_attribute_category      VARCHAR2(30),
  cons_inv_id                    NUMBER(15),
  cons_inv_id_to                 NUMBER(15),
  rule_set_id                    NUMBER,
  line_ediscounted               NUMBER,
  tax_ediscounted                NUMBER,
  freight_ediscounted            NUMBER,
  charges_ediscounted            NUMBER,
  line_uediscounted              NUMBER,
  tax_uediscounted               NUMBER,
  freight_uediscounted           NUMBER,
  charges_uediscounted           NUMBER,
  receivables_trx_id             NUMBER(15),
  on_account_customer            NUMBER(15),
  mrc_amount_applied             VARCHAR2(2000),
  mrc_amount_applied_from        VARCHAR2(2000),
  mrc_display                    VARCHAR2(2000),
  mrc_status                     VARCHAR2(2000),
  mrc_payment_schedule_id        VARCHAR2(2000),
  mrc_cash_receipt_id            VARCHAR2(2000),
  mrc_gl_posted_date             VARCHAR2(2000),
  mrc_posting_control_id         VARCHAR2(2000),
  mrc_acctd_amount_applied_from  VARCHAR2(2000),
  mrc_acctd_amount_applied_to    VARCHAR2(2000),
  mrc_acctd_earned_disc_taken    VARCHAR2(2000),
  mrc_acctd_unearned_disc_taken  VARCHAR2(2000),
  edisc_tax_acct_rule            VARCHAR2(3),
  unedisc_tax_acct_rule          VARCHAR2(3),
  link_to_trx_hist_id            NUMBER(15),
  link_to_customer_trx_id        NUMBER(15),
  application_ref_type           VARCHAR2(30),
  application_ref_id             NUMBER(15),
  application_ref_num            VARCHAR2(30),
  chargeback_customer_trx_id     NUMBER(15),
  secondary_application_ref_id   NUMBER(15),
  payment_set_id                 NUMBER(15),
  application_ref_reason         VARCHAR2(30),
  customer_reference             VARCHAR2(100),
  customer_reason                VARCHAR2(30),
  applied_rec_app_id             NUMBER(15),
  secondary_application_ref_type VARCHAR2(30),
  secondary_application_ref_num  VARCHAR2(30),
  event_id                       NUMBER(15),
  upgrade_method                 VARCHAR2(30),
  ax_accounted_flag              VARCHAR2(1)
)
