-- Create table
create table BACKUP.EVN_AP_INVOICE_PAYMENTS_ALL
(
  accounting_event_id            NUMBER(15),
  accounting_date                DATE not null,
  accrual_posted_flag            VARCHAR2(1),
  amount                         NUMBER not null,
  cash_posted_flag               VARCHAR2(1),
  check_id                       NUMBER(15) not null,
  invoice_id                     NUMBER(15) not null,
  invoice_payment_id             NUMBER(15) not null,
  last_updated_by                NUMBER(15) not null,
  last_update_date               DATE not null,
  payment_num                    NUMBER(15) not null,
  period_name                    VARCHAR2(15) not null,
  posted_flag                    VARCHAR2(1) not null,
  set_of_books_id                NUMBER(15) not null,
  accts_pay_code_combination_id  NUMBER(15),
  asset_code_combination_id      NUMBER(15),
  created_by                     NUMBER(15),
  creation_date                  DATE,
  last_update_login              NUMBER(15),
  bank_account_num               VARCHAR2(30),
  bank_account_type              VARCHAR2(25),
  bank_num                       VARCHAR2(25),
  discount_lost                  NUMBER,
  discount_taken                 NUMBER,
  exchange_date                  DATE,
  exchange_rate                  NUMBER,
  exchange_rate_type             VARCHAR2(30),
  gain_code_combination_id       NUMBER(15),
  invoice_base_amount            NUMBER,
  loss_code_combination_id       NUMBER(15),
  payment_base_amount            NUMBER,
  attribute1                     VARCHAR2(150),
  attribute10                    VARCHAR2(150),
  attribute11                    VARCHAR2(150),
  attribute12                    VARCHAR2(150),
  attribute13                    VARCHAR2(150),
  attribute14                    VARCHAR2(150),
  attribute15                    VARCHAR2(150),
  attribute2                     VARCHAR2(150),
  attribute3                     VARCHAR2(150),
  attribute4                     VARCHAR2(150),
  attribute5                     VARCHAR2(150),
  attribute6                     VARCHAR2(150),
  attribute7                     VARCHAR2(150),
  attribute8                     VARCHAR2(150),
  attribute9                     VARCHAR2(150),
  attribute_category             VARCHAR2(150),
  cash_je_batch_id               NUMBER(15),
  future_pay_code_combination_id NUMBER(15),
  future_pay_posted_flag         VARCHAR2(1),
  je_batch_id                    NUMBER(15),
  electronic_transfer_id         NUMBER(15),
  assets_addition_flag           VARCHAR2(1),
  invoice_payment_type           VARCHAR2(25),
  other_invoice_id               NUMBER(15),
  org_id                         NUMBER(15),
  global_attribute_category      VARCHAR2(150),
  global_attribute1              VARCHAR2(150),
  global_attribute2              VARCHAR2(150),
  global_attribute3              VARCHAR2(150),
  global_attribute4              VARCHAR2(150),
  global_attribute5              VARCHAR2(150),
  global_attribute6              VARCHAR2(150),
  global_attribute7              VARCHAR2(150),
  global_attribute8              VARCHAR2(150),
  global_attribute9              VARCHAR2(150),
  global_attribute10             VARCHAR2(150),
  global_attribute11             VARCHAR2(150),
  global_attribute12             VARCHAR2(150),
  global_attribute13             VARCHAR2(150),
  global_attribute14             VARCHAR2(150),
  global_attribute15             VARCHAR2(150),
  global_attribute16             VARCHAR2(150),
  global_attribute17             VARCHAR2(150),
  global_attribute18             VARCHAR2(150),
  global_attribute19             VARCHAR2(150),
  global_attribute20             VARCHAR2(150),
  external_bank_account_id       NUMBER(15),
  mrc_exchange_date              VARCHAR2(2000),
  mrc_exchange_rate              VARCHAR2(2000),
  mrc_exchange_rate_type         VARCHAR2(2000),
  mrc_gain_code_combination_id   VARCHAR2(2000),
  mrc_invoice_base_amount        VARCHAR2(2000),
  mrc_loss_code_combination_id   VARCHAR2(2000),
  mrc_payment_base_amount        VARCHAR2(2000),
  reversal_flag                  VARCHAR2(1),
  reversal_inv_pmt_id            NUMBER(15),
  iban_number                    VARCHAR2(40),
  invoicing_party_id             NUMBER(15),
  invoicing_party_site_id        NUMBER(15),
  invoicing_vendor_site_id       NUMBER(15),
  remit_to_supplier_name         VARCHAR2(240),
  remit_to_supplier_id           NUMBER(15),
  remit_to_supplier_site         VARCHAR2(240),
  remit_to_supplier_site_id      NUMBER(15)
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 128K
    next 128K
    minextents 1
    maxextents unlimited
    pctincrease 0
  );
