-- Create table
create table BACKUP.EVN_AR_CASH_RECEIPTS_B3
(
  cash_receipt_id                NUMBER(15) not null,
  last_updated_by                NUMBER(15) not null,
  last_update_date               DATE not null,
  last_update_login              NUMBER(15),
  created_by                     NUMBER(15) not null,
  creation_date                  DATE not null,
  amount                         NUMBER not null,
  set_of_books_id                NUMBER(15) not null,
  currency_code                  VARCHAR2(15) not null,
  receivables_trx_id             NUMBER(15),
  pay_from_customer              NUMBER(15),
  status                         VARCHAR2(30),
  type                           VARCHAR2(20),
  receipt_number                 VARCHAR2(30),
  receipt_date                   DATE not null,
  misc_payment_source            VARCHAR2(30),
  comments                       VARCHAR2(2000),
  distribution_set_id            NUMBER(15),
  reversal_date                  DATE,
  reversal_category              VARCHAR2(20),
  reversal_reason_code           VARCHAR2(30),
  reversal_comments              VARCHAR2(240),
  exchange_rate_type             VARCHAR2(30),
  exchange_rate                  NUMBER,
  exchange_date                  DATE,
  attribute_category             VARCHAR2(30),
  attribute1                     VARCHAR2(150),
  attribute2                     VARCHAR2(150),
  attribute3                     VARCHAR2(150),
  attribute4                     VARCHAR2(150),
  attribute5                     VARCHAR2(150),
  attribute6                     VARCHAR2(150),
  attribute7                     VARCHAR2(150),
  attribute8                     VARCHAR2(150),
  attribute9                     VARCHAR2(150),
  attribute10                    VARCHAR2(150),
  remittance_bank_account_id     NUMBER(15),
  attribute11                    VARCHAR2(150),
  attribute12                    VARCHAR2(150),
  attribute13                    VARCHAR2(150),
  attribute14                    VARCHAR2(150),
  attribute15                    VARCHAR2(150),
  confirmed_flag                 VARCHAR2(1),
  customer_bank_account_id       NUMBER(15),
  customer_site_use_id           NUMBER(15),
  deposit_date                   DATE,
  program_application_id         NUMBER(15),
  program_id                     NUMBER(15),
  program_update_date            DATE,
  receipt_method_id              NUMBER(15) not null,
  request_id                     NUMBER(15),
  selected_for_factoring_flag    VARCHAR2(1),
  selected_remittance_batch_id   NUMBER(15),
  factor_discount_amount         NUMBER,
  ussgl_transaction_code         VARCHAR2(30),
  ussgl_transaction_code_context VARCHAR2(30),
  doc_sequence_value             NUMBER(15),
  doc_sequence_id                NUMBER(15),
  vat_tax_id                     NUMBER(15),
  reference_type                 VARCHAR2(30),
  reference_id                   NUMBER(15),
  customer_receipt_reference     VARCHAR2(30),
  override_remit_account_flag    VARCHAR2(1),
  org_id                         NUMBER(15),
  anticipated_clearing_date      DATE,
  global_attribute1              VARCHAR2(150),
  global_attribute2              VARCHAR2(150),
  global_attribute3              VARCHAR2(150),
  global_attribute4              VARCHAR2(150),
  global_attribute5              VARCHAR2(150),
  global_attribute6              VARCHAR2(150),
  global_attribute7              VARCHAR2(150),
  global_attribute8              VARCHAR2(150),
  global_attribute9              VARCHAR2(150),
  global_attribute10             VARCHAR2(150),
  global_attribute11             VARCHAR2(150),
  global_attribute12             VARCHAR2(150),
  global_attribute13             VARCHAR2(150),
  global_attribute14             VARCHAR2(150),
  global_attribute15             VARCHAR2(150),
  global_attribute16             VARCHAR2(150),
  global_attribute17             VARCHAR2(150),
  global_attribute18             VARCHAR2(150),
  global_attribute19             VARCHAR2(150),
  global_attribute20             VARCHAR2(150),
  global_attribute_category      VARCHAR2(30),
  issuer_name                    VARCHAR2(50),
  issue_date                     DATE,
  issuer_bank_branch_id          NUMBER(15),
  customer_bank_branch_id        NUMBER(15),
  mrc_exchange_rate_type         VARCHAR2(2000),
  mrc_exchange_rate              VARCHAR2(2000),
  mrc_exchange_date              VARCHAR2(2000),
  payment_server_order_num       VARCHAR2(80),
  approval_code                  VARCHAR2(80),
  address_verification_code      VARCHAR2(80),
  tax_rate                       NUMBER,
  actual_value_date              DATE,
  postmark_date                  DATE,
  application_notes              VARCHAR2(2000),
  unique_reference               VARCHAR2(32),
  promise_source                 VARCHAR2(30),
  rec_version_number             NUMBER(15),
  cc_error_code                  VARCHAR2(80),
  cc_error_text                  VARCHAR2(255),
  cc_error_flag                  VARCHAR2(1),
  remit_bank_acct_use_id         NUMBER(15),
  old_customer_bank_branch_id    NUMBER(15),
  old_issuer_bank_branch_id      NUMBER(15),
  legal_entity_id                NUMBER(15),
  payment_trxn_extension_id      NUMBER(15),
  ax_accounted_flag              VARCHAR2(1),
  old_customer_bank_account_id   NUMBER(15),
  cash_appln_owner_id            NUMBER(15),
  work_item_assignment_date      DATE,
  work_item_review_date          DATE,
  work_item_status_code          VARCHAR2(30),
  work_item_review_note          VARCHAR2(2000),
  prev_pay_from_customer         NUMBER(15),
  prev_customer_site_use_id      NUMBER(15),
  work_item_exception_reason     VARCHAR2(30),
  automatch_set_id               NUMBER(15),
  autoapply_flag                 VARCHAR2(1),
  seq_type_last                  VARCHAR2(1)
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 128K
    next 128K
    minextents 1
    maxextents unlimited
    pctincrease 0
  );
