-- Create table
create table BACKUP.EVN_ZX_REC_NREC_DIST
(
  rec_nrec_tax_dist_id           NUMBER(15) not null,
  application_id                 NUMBER not null,
  entity_code                    VARCHAR2(30) not null,
  event_class_code               VARCHAR2(30) not null,
  event_type_code                VARCHAR2(30) not null,
  tax_event_class_code           VARCHAR2(30),
  tax_event_type_code            VARCHAR2(30),
  trx_id                         NUMBER not null,
  trx_line_id                    NUMBER not null,
  trx_line_number                NUMBER,
  tax_line_id                    NUMBER(15) not null,
  tax_line_number                NUMBER not null,
  trx_line_dist_id               NUMBER not null,
  item_dist_number               NUMBER,
  content_owner_id               NUMBER(15),
  rec_nrec_tax_dist_number       NUMBER not null,
  tax_regime_id                  NUMBER(15),
  tax_regime_code                VARCHAR2(30),
  tax_id                         NUMBER(15),
  tax                            VARCHAR2(30),
  tax_status_id                  NUMBER(15),
  tax_status_code                VARCHAR2(30),
  tax_rate_id                    NUMBER(15),
  tax_rate_code                  VARCHAR2(150),
  tax_rate                       NUMBER,
  inclusive_flag                 VARCHAR2(1),
  recovery_type_id               NUMBER(15),
  recovery_type_code             VARCHAR2(30),
  recovery_rate_id               NUMBER(15),
  recovery_rate_code             VARCHAR2(150),
  rec_nrec_rate                  NUMBER not null,
  rec_type_rule_flag             VARCHAR2(1),
  new_rec_rate_code_flag         VARCHAR2(1),
  recoverable_flag               VARCHAR2(1) not null,
  reverse_flag                   VARCHAR2(1),
  historical_flag                VARCHAR2(1),
  reversed_tax_dist_id           NUMBER,
  rec_nrec_tax_amt               NUMBER not null,
  rec_nrec_tax_amt_tax_curr      NUMBER,
  rec_nrec_tax_amt_funcl_curr    NUMBER,
  intended_use                   VARCHAR2(30),
  project_id                     NUMBER,
  task_id                        NUMBER,
  award_id                       NUMBER,
  expenditure_type               VARCHAR2(30),
  expenditure_organization_id    NUMBER,
  expenditure_item_date          DATE,
  rec_rate_det_rule_flag         VARCHAR2(1),
  ledger_id                      NUMBER(15),
  summary_tax_line_id            NUMBER(15),
  record_type_code               VARCHAR2(30),
  currency_conversion_date       DATE,
  currency_conversion_type       VARCHAR2(30),
  currency_conversion_rate       NUMBER,
  tax_currency_conversion_date   DATE,
  tax_currency_conversion_type   VARCHAR2(30),
  tax_currency_conversion_rate   NUMBER,
  trx_currency_code              VARCHAR2(15),
  tax_currency_code              VARCHAR2(15),
  trx_line_dist_amt              NUMBER,
  trx_line_dist_tax_amt          NUMBER,
  orig_rec_nrec_rate             NUMBER,
  orig_rec_rate_code             VARCHAR2(150),
  orig_rec_nrec_tax_amt          NUMBER,
  orig_rec_nrec_tax_amt_tax_curr NUMBER,
  unrounded_rec_nrec_tax_amt     NUMBER,
  applicability_result_id        NUMBER(15),
  rec_rate_result_id             NUMBER(15),
  backward_compatibility_flag    VARCHAR2(1),
  overridden_flag                VARCHAR2(1),
  self_assessed_flag             VARCHAR2(1),
  freeze_flag                    VARCHAR2(1),
  posting_flag                   VARCHAR2(1),
  attribute_category             VARCHAR2(150),
  attribute1                     VARCHAR2(150),
  attribute2                     VARCHAR2(150),
  attribute3                     VARCHAR2(150),
  attribute4                     VARCHAR2(150),
  attribute5                     VARCHAR2(150),
  attribute6                     VARCHAR2(150),
  attribute7                     VARCHAR2(150),
  attribute8                     VARCHAR2(150),
  attribute9                     VARCHAR2(150),
  attribute10                    VARCHAR2(150),
  attribute11                    VARCHAR2(150),
  attribute12                    VARCHAR2(150),
  attribute13                    VARCHAR2(150),
  attribute14                    VARCHAR2(150),
  attribute15                    VARCHAR2(150),
  global_attribute_category      VARCHAR2(150),
  global_attribute1              VARCHAR2(150),
  global_attribute2              VARCHAR2(150),
  global_attribute3              VARCHAR2(150),
  global_attribute4              VARCHAR2(150),
  global_attribute5              VARCHAR2(150),
  global_attribute6              VARCHAR2(150),
  global_attribute7              VARCHAR2(150),
  global_attribute8              VARCHAR2(150),
  global_attribute9              VARCHAR2(150),
  global_attribute10             VARCHAR2(150),
  global_attribute11             VARCHAR2(150),
  global_attribute12             VARCHAR2(150),
  global_attribute13             VARCHAR2(150),
  global_attribute14             VARCHAR2(150),
  global_attribute15             VARCHAR2(150),
  gl_date                        DATE,
  created_by                     NUMBER(15) not null,
  creation_date                  DATE not null,
  last_updated_by                NUMBER(15) not null,
  last_update_login              NUMBER(15),
  last_update_date               DATE not null,
  ref_doc_application_id         NUMBER,
  ref_doc_entity_code            VARCHAR2(30),
  ref_doc_event_class_code       VARCHAR2(30),
  ref_doc_trx_id                 NUMBER,
  ref_doc_line_id                NUMBER,
  ref_doc_dist_id                NUMBER,
  minimum_accountable_unit       NUMBER,
  precision                      NUMBER,
  rounding_rule_code             VARCHAR2(30),
  taxable_amt                    NUMBER,
  taxable_amt_tax_curr           NUMBER,
  taxable_amt_funcl_curr         NUMBER,
  tax_only_line_flag             VARCHAR2(1),
  unrounded_taxable_amt          NUMBER,
  legal_entity_id                NUMBER,
  account_ccid                   NUMBER,
  account_string                 VARCHAR2(2000),
  prd_tax_amt                    NUMBER,
  prd_tax_amt_tax_curr           NUMBER,
  prd_tax_amt_funcl_curr         NUMBER,
  prd_total_tax_amt              NUMBER,
  prd_total_tax_amt_tax_curr     NUMBER,
  prd_total_tax_amt_funcl_curr   NUMBER,
  applied_from_tax_dist_id       NUMBER,
  adjusted_doc_tax_dist_id       NUMBER,
  func_curr_rounding_adjustment  NUMBER,
  global_attribute16             VARCHAR2(150),
  global_attribute17             VARCHAR2(150),
  global_attribute18             VARCHAR2(150),
  global_attribute19             VARCHAR2(150),
  global_attribute20             VARCHAR2(150),
  last_manual_entry              VARCHAR2(30),
  tax_apportionment_line_number  NUMBER,
  ref_doc_tax_dist_id            NUMBER,
  mrc_tax_dist_flag              VARCHAR2(1),
  mrc_link_to_tax_dist_id        NUMBER,
  tax_apportionment_flag         VARCHAR2(1),
  rate_tax_factor                NUMBER,
  ref_doc_per_unit_nrec_tax_amt  NUMBER,
  per_unit_nrec_tax_amt          NUMBER,
  trx_line_dist_qty              NUMBER,
  ref_doc_trx_line_dist_qty      NUMBER,
  price_diff                     NUMBER,
  qty_diff                       NUMBER,
  per_trx_curr_unit_nr_amt       NUMBER,
  ref_per_trx_curr_unit_nr_amt   NUMBER,
  ref_doc_curr_conv_rate         NUMBER,
  unit_price                     NUMBER,
  ref_doc_unit_price             NUMBER,
  applied_to_doc_curr_conv_rate  NUMBER,
  trx_number                     VARCHAR2(150),
  trx_level_type                 VARCHAR2(30),
  ref_doc_trx_level_type         VARCHAR2(30),
  object_version_number          NUMBER not null,
  orig_ap_chrg_dist_num          NUMBER,
  orig_ap_chrg_dist_id           NUMBER,
  orig_ap_tax_dist_num           NUMBER,
  orig_ap_tax_dist_id            NUMBER,
  internal_organization_id       NUMBER,
  tax_jurisdiction_id            NUMBER(15),
  def_rec_settlement_option_code VARCHAR2(30),
  account_source_tax_rate_id     NUMBER(15),
  orig_gl_date                   DATE
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 128K
    next 128K
    minextents 1
    maxextents unlimited
    pctincrease 0
  );
