-- Create table
create table BACKUP.EVN_RA_CUST_TRX_LINE_ALL_B3
(
  customer_trx_line_id           NUMBER(15) not null,
  last_update_date               DATE not null,
  last_updated_by                NUMBER(15) not null,
  creation_date                  DATE not null,
  created_by                     NUMBER(15) not null,
  last_update_login              NUMBER(15),
  customer_trx_id                NUMBER(15) not null,
  line_number                    NUMBER not null,
  set_of_books_id                NUMBER(15) not null,
  reason_code                    VARCHAR2(30),
  inventory_item_id              NUMBER(15),
  description                    VARCHAR2(240),
  previous_customer_trx_id       NUMBER(15),
  previous_customer_trx_line_id  NUMBER(15),
  quantity_ordered               NUMBER,
  quantity_credited              NUMBER,
  quantity_invoiced              NUMBER,
  unit_standard_price            NUMBER,
  unit_selling_price             NUMBER,
  sales_order                    VARCHAR2(50),
  sales_order_revision           NUMBER,
  sales_order_line               VARCHAR2(30),
  sales_order_date               DATE,
  accounting_rule_id             NUMBER(15),
  accounting_rule_duration       NUMBER(15),
  line_type                      VARCHAR2(20) not null,
  attribute_category             VARCHAR2(30),
  attribute1                     VARCHAR2(150),
  attribute2                     VARCHAR2(150),
  attribute3                     VARCHAR2(150),
  attribute4                     VARCHAR2(150),
  attribute5                     VARCHAR2(150),
  attribute6                     VARCHAR2(150),
  attribute7                     VARCHAR2(150),
  attribute8                     VARCHAR2(150),
  attribute9                     VARCHAR2(150),
  attribute10                    VARCHAR2(150),
  request_id                     NUMBER(15),
  program_application_id         NUMBER(15),
  program_id                     NUMBER(15),
  program_update_date            DATE,
  rule_start_date                DATE,
  initial_customer_trx_line_id   NUMBER(15),
  interface_line_context         VARCHAR2(30),
  interface_line_attribute1      VARCHAR2(150),
  interface_line_attribute2      VARCHAR2(150),
  interface_line_attribute3      VARCHAR2(150),
  interface_line_attribute4      VARCHAR2(150),
  interface_line_attribute5      VARCHAR2(150),
  interface_line_attribute6      VARCHAR2(150),
  interface_line_attribute7      VARCHAR2(150),
  interface_line_attribute8      VARCHAR2(150),
  sales_order_source             VARCHAR2(50),
  taxable_flag                   VARCHAR2(1),
  extended_amount                NUMBER not null,
  revenue_amount                 NUMBER,
  autorule_complete_flag         VARCHAR2(1),
  link_to_cust_trx_line_id       NUMBER(15),
  attribute11                    VARCHAR2(150),
  attribute12                    VARCHAR2(150),
  attribute13                    VARCHAR2(150),
  attribute14                    VARCHAR2(150),
  attribute15                    VARCHAR2(150),
  tax_precedence                 NUMBER,
  tax_rate                       NUMBER,
  item_exception_rate_id         NUMBER(15),
  tax_exemption_id               NUMBER(15),
  memo_line_id                   NUMBER(15),
  autorule_duration_processed    NUMBER(15),
  uom_code                       VARCHAR2(3),
  default_ussgl_transaction_code VARCHAR2(30),
  default_ussgl_trx_code_context VARCHAR2(30),
  interface_line_attribute10     VARCHAR2(150),
  interface_line_attribute11     VARCHAR2(150),
  interface_line_attribute12     VARCHAR2(150),
  interface_line_attribute13     VARCHAR2(150),
  interface_line_attribute14     VARCHAR2(150),
  interface_line_attribute15     VARCHAR2(150),
  interface_line_attribute9      VARCHAR2(150),
  vat_tax_id                     NUMBER(15),
  autotax                        VARCHAR2(1),
  last_period_to_credit          NUMBER,
  item_context                   VARCHAR2(30),
  tax_exempt_flag                VARCHAR2(1),
  tax_exempt_number              VARCHAR2(80),
  tax_exempt_reason_code         VARCHAR2(30),
  tax_vendor_return_code         VARCHAR2(30),
  sales_tax_id                   NUMBER(15),
  location_segment_id            NUMBER(15),
  movement_id                    NUMBER(15),
  org_id                         NUMBER(15),
  wh_update_date                 DATE,
  global_attribute1              VARCHAR2(150),
  global_attribute2              VARCHAR2(150),
  global_attribute3              VARCHAR2(150),
  global_attribute4              VARCHAR2(150),
  global_attribute5              VARCHAR2(150),
  global_attribute6              VARCHAR2(150),
  global_attribute7              VARCHAR2(150),
  global_attribute8              VARCHAR2(150),
  global_attribute9              VARCHAR2(150),
  global_attribute10             VARCHAR2(150),
  global_attribute11             VARCHAR2(150),
  global_attribute12             VARCHAR2(150),
  global_attribute13             VARCHAR2(150),
  global_attribute14             VARCHAR2(150),
  global_attribute15             VARCHAR2(150),
  global_attribute16             VARCHAR2(150),
  global_attribute17             VARCHAR2(150),
  global_attribute18             VARCHAR2(150),
  global_attribute19             VARCHAR2(150),
  global_attribute20             VARCHAR2(150),
  global_attribute_category      VARCHAR2(30),
  gross_unit_selling_price       NUMBER,
  gross_extended_amount          NUMBER,
  amount_includes_tax_flag       VARCHAR2(1),
  taxable_amount                 NUMBER,
  warehouse_id                   NUMBER(15),
  translated_description         VARCHAR2(1000),
  extended_acctd_amount          NUMBER,
  br_ref_customer_trx_id         NUMBER(15),
  br_ref_payment_schedule_id     NUMBER(15),
  br_adjustment_id               NUMBER(15),
  mrc_extended_acctd_amount      VARCHAR2(2000),
  payment_set_id                 NUMBER(15),
  contract_line_id               NUMBER,
  source_data_key1               VARCHAR2(150),
  source_data_key2               VARCHAR2(150),
  source_data_key3               VARCHAR2(150),
  source_data_key4               VARCHAR2(150),
  source_data_key5               VARCHAR2(150),
  invoiced_line_acctg_level      VARCHAR2(15),
  override_auto_accounting_flag  VARCHAR2(1),
  ship_to_customer_id            NUMBER(15),
  ship_to_address_id             NUMBER(15),
  ship_to_site_use_id            NUMBER(15),
  ship_to_contact_id             NUMBER(15),
  historical_flag                VARCHAR2(1),
  tax_line_id                    NUMBER(15),
  line_recoverable               NUMBER,
  tax_recoverable                NUMBER,
  tax_classification_code        VARCHAR2(30),
  amount_due_remaining           NUMBER,
  acctd_amount_due_remaining     NUMBER,
  amount_due_original            NUMBER,
  acctd_amount_due_original      NUMBER,
  chrg_amount_remaining          NUMBER,
  chrg_acctd_amount_remaining    NUMBER,
  frt_adj_remaining              NUMBER,
  frt_adj_acctd_remaining        NUMBER,
  frt_ed_amount                  NUMBER,
  frt_ed_acctd_amount            NUMBER,
  frt_uned_amount                NUMBER,
  frt_uned_acctd_amount          NUMBER,
  deferral_exclusion_flag        VARCHAR2(1),
  rule_end_date                  DATE,
  payment_trxn_extension_id      NUMBER(15),
  interest_line_id               NUMBER(15)
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 128K
    next 128K
    minextents 1
    maxextents unlimited
    pctincrease 0
  );
