-- Create table
create table BACKUP.EVN_AR_PAYMENT_SCHEDULES_B3
(
  payment_schedule_id            NUMBER(15) not null,
  staged_dunning_level           NUMBER(2),
  dunning_level_override_date    DATE,
  last_update_date               DATE not null,
  last_updated_by                NUMBER(15) not null,
  creation_date                  DATE not null,
  created_by                     NUMBER(15) not null,
  last_update_login              NUMBER(15),
  due_date                       DATE not null,
  amount_due_original            NUMBER not null,
  amount_due_remaining           NUMBER not null,
  number_of_due_dates            NUMBER(15) not null,
  status                         VARCHAR2(30) not null,
  invoice_currency_code          VARCHAR2(15) not null,
  class                          VARCHAR2(20) not null,
  cust_trx_type_id               NUMBER(15),
  customer_id                    NUMBER(15),
  customer_site_use_id           NUMBER(15),
  customer_trx_id                NUMBER(15),
  cash_receipt_id                NUMBER(15),
  associated_cash_receipt_id     NUMBER(15),
  term_id                        NUMBER(15),
  terms_sequence_number          NUMBER(15),
  gl_date_closed                 DATE not null,
  actual_date_closed             DATE not null,
  discount_date                  DATE,
  amount_line_items_original     NUMBER,
  amount_line_items_remaining    NUMBER,
  amount_applied                 NUMBER,
  amount_adjusted                NUMBER,
  amount_in_dispute              NUMBER,
  amount_credited                NUMBER,
  receivables_charges_charged    NUMBER,
  receivables_charges_remaining  NUMBER,
  freight_original               NUMBER,
  freight_remaining              NUMBER,
  tax_original                   NUMBER,
  tax_remaining                  NUMBER,
  discount_original              NUMBER,
  discount_remaining             NUMBER,
  discount_taken_earned          NUMBER,
  discount_taken_unearned        NUMBER,
  in_collection                  VARCHAR2(1),
  cash_applied_id_last           NUMBER,
  cash_applied_date_last         DATE,
  cash_applied_amount_last       NUMBER,
  cash_applied_status_last       VARCHAR2(30),
  cash_gl_date_last              DATE,
  cash_receipt_id_last           NUMBER(15),
  cash_receipt_date_last         DATE,
  cash_receipt_amount_last       NUMBER,
  cash_receipt_status_last       VARCHAR2(30),
  exchange_rate_type             VARCHAR2(30),
  exchange_date                  DATE,
  exchange_rate                  NUMBER,
  adjustment_id_last             NUMBER(15),
  adjustment_date_last           DATE,
  adjustment_gl_date_last        DATE,
  adjustment_amount_last         NUMBER,
  follow_up_date_last            DATE,
  follow_up_code_last            VARCHAR2(30),
  promise_date_last              DATE,
  promise_amount_last            NUMBER,
  collector_last                 NUMBER(15),
  call_date_last                 DATE,
  trx_number                     VARCHAR2(30),
  trx_date                       DATE,
  attribute_category             VARCHAR2(30),
  attribute1                     VARCHAR2(150),
  attribute2                     VARCHAR2(150),
  attribute3                     VARCHAR2(150),
  attribute4                     VARCHAR2(150),
  attribute5                     VARCHAR2(150),
  attribute6                     VARCHAR2(150),
  attribute7                     VARCHAR2(150),
  attribute8                     VARCHAR2(150),
  attribute9                     VARCHAR2(150),
  attribute10                    VARCHAR2(150),
  reversed_cash_receipt_id       NUMBER(15),
  amount_adjusted_pending        NUMBER,
  attribute11                    VARCHAR2(150),
  attribute12                    VARCHAR2(150),
  attribute13                    VARCHAR2(150),
  attribute14                    VARCHAR2(150),
  attribute15                    VARCHAR2(150),
  gl_date                        DATE not null,
  acctd_amount_due_remaining     NUMBER not null,
  program_application_id         NUMBER(15),
  program_id                     NUMBER(15),
  program_update_date            DATE,
  receipt_confirmed_flag         VARCHAR2(1),
  request_id                     NUMBER(15),
  selected_for_receipt_batch_id  NUMBER(15),
  last_charge_date               DATE,
  second_last_charge_date        DATE,
  dispute_date                   DATE,
  org_id                         NUMBER(15),
  global_attribute1              VARCHAR2(150),
  global_attribute2              VARCHAR2(150),
  global_attribute3              VARCHAR2(150),
  global_attribute4              VARCHAR2(150),
  global_attribute5              VARCHAR2(150),
  global_attribute6              VARCHAR2(150),
  global_attribute7              VARCHAR2(150),
  global_attribute8              VARCHAR2(150),
  global_attribute9              VARCHAR2(150),
  global_attribute10             VARCHAR2(150),
  global_attribute11             VARCHAR2(150),
  global_attribute12             VARCHAR2(150),
  global_attribute13             VARCHAR2(150),
  global_attribute14             VARCHAR2(150),
  global_attribute15             VARCHAR2(150),
  global_attribute16             VARCHAR2(150),
  global_attribute17             VARCHAR2(150),
  global_attribute18             VARCHAR2(150),
  global_attribute19             VARCHAR2(150),
  global_attribute20             VARCHAR2(150),
  global_attribute_category      VARCHAR2(30),
  cons_inv_id                    NUMBER(15),
  cons_inv_id_rev                NUMBER(15),
  exclude_from_dunning_flag      VARCHAR2(1),
  mrc_customer_trx_id            VARCHAR2(2000),
  mrc_exchange_rate_type         VARCHAR2(2000),
  mrc_exchange_date              VARCHAR2(2000),
  mrc_exchange_rate              VARCHAR2(2000),
  mrc_acctd_amount_due_remaining VARCHAR2(2000),
  br_amount_assigned             NUMBER,
  reserved_type                  VARCHAR2(30),
  reserved_value                 NUMBER(15),
  active_claim_flag              VARCHAR2(1),
  exclude_from_cons_bill_flag    VARCHAR2(1),
  payment_approval               VARCHAR2(30)
)
tablespace APPS_TS_TX_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 128K
    next 128K
    minextents 1
    maxextents unlimited
    pctincrease 0
  );
